
/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    checkstyle
}

tasks.withType<Checkstyle>().configureEach {
    ignoreFailures = true
    maxWarnings = 0
    if (name == "checkstyleTest") {
        enabled = false
    }

}
